### ISSUE TITLE
Interpreter bugs

### ISSUE THREAD

**Issue by BambooL** [andreabolognani/beef#1]
I found some code cannot be handled by beef, it does not output any error messages but just keep parsing it for very long time. It might fall into some infinite loop inside the interpreter that requires some fix. Please see the example code:
Example (1)
<<+<<<<<<<<<<...........>>>>>>>>>>,,>>>------------................................>>>>>>>
Example (2)
,,,...,,,,,.........................<<-----------.....>>>>...............>>>---------------

**Comment by andreabolognani** [comment]
Hi, sorry for taking a while to respond.

Beef is perfectly capable of handling those programs, it's just that in both cases some input is needed and execution won't be able to move forward until you provide it:

```
$ beef example1.b 
some input
��������������������������������$
$ beef example2.b 
some input
mmmppppppppppppppppppppppppp�����$
```

I picked another random Brainfuck interpreter and confirmed that its behavior was the same, so I'm pretty confident Beef is working as expected.

Thanks for your interest in Beef! :)
